# Specify the build settings
[build]
  # The directory where your built HTML, CSS, and JavaScript files are located
  publish = "build/"

  # The command to build your project (customize this according to your project setup)
  command = "npm run build"

  # Run your custom script as part of the build process
  # Adjust the path to your script as needed
  functions = "src/scripts/extractMdxFrontmatter.js"

# Configure your environment variables (if needed)
# [build.environment]
#   VARIABLE_NAME = "variable_value"

# Define custom headers and redirects (if needed)
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Header-Name = "Header-Value"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Specify the version of Node.js to use (if your project has specific Node.js requirements)
# [build.environment]
#   NODE_VERSION = "14"

# Specify any post-processing or other build settings (if needed)
# [build]
#   command = "npm run build"
#   functions = "lambda"

# If your project uses environment variables stored in a .env file (optional)
# [build.environment]
#   MY_ENV_VAR = "my_value"

# Define custom functions (if needed)
# [functions]
#   myFunction = "path/to/my/function.js"
